version: 1.0.1-BETA
author: ChrisWille2856
name: LotusGamingSystem
main: eu.lotusgc.mc.main.Main
api-version: 1.20

commands:
    s:
    profile:
    gamemode:
        alias: gm
    cc:
        alias: chatclear
    invsee:
    sethome:
    listhomes:
    delhome:
    home:
    time:
    msg:
    msgopt:
    r:
    fly:
    workbench:
        alias: wb
    weather:
    sb:
    clearlag:
    afk:
    
    # INFO: ALIAS IS NOT BEING DETECTED! BUGFIX PLS