version: 1.0.1-BETA
author: ChrisWille2856
name: LotusGamingSystem
main: eu.lotusgc.mc.main.Main
api-version: 1.20

commands:
    s:
    profile:
    gamemode:
        aliases: gm
    cc:
        aliases: chatclear
    invsee:
    sethome:
    listhomes:
    delhome:
    home:
    time:
    msg:
    msgopt:
    r:
    fly:
    workbench:
        aliases: wb
    weather:
    sb:
    clearlag:
    afk:
    